web/site/__init__.py
# -*- coding: utf-8 -*-

import json, random, urlparse
from datetime import datetime, timedelta
from flask import (Blueprint, abort, redirect, request,
                   url_for, session, Markup, jsonify, current_app,
                   make_response)
from flask.ext.login import current_user

from ext import csrf, cache
from modules.apishop import ApishopConfig, api_connect
from modules.catalog.models import (Category, Offer, Cart, Order, Review,
                                    Region, DeliveryMethod, PaymentMethod, RegionDelivery)
from modules.pages.models import Page
from modules.dispatcher.models import Dispatcher
from modules.catalog.dispatchers import CategoryDispatcher, OfferDispatcher, VendorDispatcher
from modules.pages.dispatchers import PageDispatcher
from modules.subscribe.models import Subscriber
from modules.banners.models import Banner

from forms import OrderForm, SubscribeForm
from helpers import render_template
from utils.text import clear_tags_and_make_lines
from utils.json import request_wants_json


site = Blueprint('site', __name__)

d_map = {
    'category': CategoryDispatcher,
    'offer': OfferDispatcher,
    'vendor': VendorDispatcher,
    'page': PageDispatcher
}


@site.context_processor
def site_context():
    return dict(current_year=datetime.now().year,
                default_title=current_app.config.get('DEFAULT_TITLE'),
                default_title_separator=current_app.config.get('DEFAULT_TITLE_SEPARATOR', ' | '),
                subscribe_form=SubscribeForm(),
                is_subscribed=session.get('is_subscribed', False))


@site.before_request
def set_permanent_session():
    session.permanent = True


# Should be commented or deleted
#
# @site.route('/email/<typ>/')
# def email(typ):
#     return render_template('email/{}.html'.format(typ))


@site.route('/')
def index():
    return render_template('index.html',
                           popular_offers=Offer.get_popular()[:8],
                           special_offers=Offer.get_special_offers()[:12],
                           banners=Banner.get_banners())


@site.route('/sitemap.xml')
def sitemap():
    url_root = request.url_root

    categories = [[urlparse.urljoin(url_root, url_for('site.dispatcher', path=cat.path)),
                   cat.updated_at.strftime('%Y-%m-%d') if cat.updated_at is not None else None]
                  for cat in Category.objects.only('path', 'updated_at').order_by('+position')]

    offers = [[urlparse.urljoin(url_root, url_for('site.dispatcher', path=o.path)),
               o.updated_at.strftime('%Y-%m-%d') if o.updated_at is not None else None]
             for o in Offer.objects.only('path', 'updated_at').order_by('+path')]

    pages = [[urlparse.urljoin(url_root, url_for('site.dispatcher', path=page.path)),
              page.updated_at.strftime('%Y-%m-%d') if page.updated_at is not None else None]
             for page in Page.objects.only('path', 'updated_at').order_by('+position')]

    now = datetime.now().strftime('%Y-%m-%d')
    temp_pages = [[urlparse.urljoin(url_root, url_for('site.{}'.format(rule))), now]
                  for rule in ('upto1000', 'specials')]

    context = {'root': [url_root, datetime.now().strftime('%Y-%m-%d')],
               'categories': categories,
               'offers': offers,
               'pages': pages,
               'temp_pages': temp_pages}

    sitemap = render_template('misc/sitemap.xml', **context)
    response = make_response(sitemap)
    response.headers['Content-Type'] = 'application/xml'

    return response


@site.route('/specials/')
def specials():
    offers = Offer.objects(special__ne=None).order_by('price.ru')
    return render_template('specials.html', offers=offers)


@site.route('/up-to-1000/')
def upto1000():
    offers = Offer.objects(price__ru__lt=1000.00,
                           available=True).order_by('-stats.populatiry')
    return render_template('upto1000.html', offers=offers)


@site.route('/search/')
def search():
    s = request.args.get('s', '')

    if s:
        offers = Offer.objects.search_text(s).order_by('$text_score')
    else:
        offers = []

    return render_template('search.html',
                           offers=offers,
                           s=s)

@site.route('/profile/')
def profile():

    return render_template('profile.html')


@site.errorhandler(404)
def page_not_found(e):
    context = {'error': e}
    context['title'] = u'Страница не найдена'
    context['error_name'] = u'Ошибка 404'
    context['error_text'] = u'Вы перешли по неправильной ссылке<br />или страница была удалена'
    return render_template('errors.html', **context), e.code


@site.errorhandler(403)
def page_not_found(e):
    context = {'error': e}
    context['title'] = u'Страница не доступна'
    context['error_name'] = u'Ошибка 403'
    context['error_text'] = u'У вас нет прав для<br />доступа к этой странице'
    return render_template('errors.html', **context), e.code


@site.route('/cart/', methods=['GET', 'POST'])
def cart():
    cart = Cart.get_or_create()

    if request.method == 'POST':
        offer_id = request.form.get('offer_id', None)

        if offer_id:
            quantity = request.form.get('quantity', 1)
            variant = request.form.get('variant', None)
            cart.add_offer(offer_id, quantity, variant)

            return redirect(url_for('site.cart'))

    return render_template('cart.html')


@site.route('/order/', defaults={'order_id': None}, methods=['POST'])
@site.route('/order/<order_id>/')
def order(order_id=None):
    if not order_id and request.method == 'POST':
        cart = Cart.get_or_create()
        order_id = cart.send_order(request.form)
        if order_id:
            return json.dumps(dict(order_id=order_id, backurl=url_for('site.order', order_id=order_id)))
        else:
            error = u'Что-то пошло не так и заказ не отправился'
            return json.dumps(dict(error=error))

    order = Order.objects.get_or_404(id=order_id)

    region_id = order.userinfo.get('region_id', None)
    payment_id = order.userinfo.get('payment_method', None)
    delivery_id = order.userinfo.get('delivery_method', None)

    region = Region.objects(id=region_id).first() if region_id else None
    payment = PaymentMethod.objects(id=payment_id).first() if payment_id else None
    delivery = DeliveryMethod.objects(id=delivery_id).first() if delivery_id else None

    # conf = ApishopConfig.get_config()
    # conn = api_connect(conf)
    #
    # from pprint import pprint
    # for key, item in conn.get_order_states().items():
    #     print key, item
    #
    # info = conn.get_orders_info(str(order.apishop_id))[0]
    #
    # for attr in vars(info):
    #     print u'{}\t\t\t: {}'.format(attr, getattr(info, attr, None))

    return render_template('order.html',
                           order=order,
                           region=region,
                           payment=payment,
                           delivery=delivery)


@site.route('/order/<order_id>/api/upsale/', methods=['GET', 'POST'])
def order_upsale(order_id):
    if request_wants_json():
        order = Order.objects(id=order_id).first()

        if order and request.method == 'GET':
            offers = order.get_relevant_offers(3)

            if not offers.count():
                return None

            favorites = session.get('favorites', [])
            offers = [dict(id=str(offer.id),
                           name=offer.name,
                           url=url_for('site.dispatcher', path=offer.path),
                           favorited=str(offer.id) in favorites,
                           category=dict(name=offer.parent.name,
                                         url=url_for('site.dispatcher',
                                                     path=offer.parent.path)),
                           price=offer.get_price(),
                           oldprice=offer.get_oldprice,
                           timer=offer.get_timer,
                           picture=offer.get_picture()) for offer in offers]

            return jsonify(offers=offers)

        if order and request.method == 'POST':
            offer_id = request.form.get('offer_id', None)
            if not offer_id:
                return jsonify(error=True)

            offer = Offer.objects(id=offer_id).first()
            if not offer:
                return jsonify(error=True)

            quantity = request.form.get('quantity', 1)
            variant_id = request.form.get('variant_id', None)
            variant = offer.get_variant(variant_id)

            sale = send_upsale(order, offer, quantity, variant)

            order.add_offer(offer, quantity, variant)

            # item = {
            #     'picture': offer.get_picture(),
            #     'name': offer.name,
            #     'price': offer.get_price(),
            #     'quantity': quantity,
            #     'total': offer.get_price() * quantity,
            #     'url': url_for('site.dispatcher', path=offer.path),
            # }

            return jsonify(error=False)

    return abort(404)


@site.route('/cart/api/', defaults={'offer_id': None}, methods=['POST'])
@site.route('/cart/api/<offer_id>/', methods=['POST'])
@csrf.exempt
def cart_api(offer_id=None):

    if offer_id:
        variants = []
        offer = Offer.objects(id=offer_id).first()
        if offer:
            variants = [dict(name=variant.name,
                             count=variant.store_count,
                             id=variant.aid) for variant in offer.variants]

        return json.dumps(dict(variants=variants))
    else:
        cart = Cart.get_or_create()
        form = request.form

        offer_id = form.get('offer_id', None)
        if offer_id:
            remove = True if form.get('remove') == 'true' else False
            variant_id = form.get('variant_id')
            if remove:
                cart.remove_offer(offer_id, variant_id)
            else:

templates/macros/__all.html
{% macro render_breadcrumbs() %}
    <div class="row">
        <div class="col-12">
            <ul class="breadcrumbs">
                {% if not breadcrumbs %}
                    <li class="breadcrumbs__item"><a href="{{ url_for('site.index') }}" class="breadcrumbs__item-link"><span class="breadcrumbs__item-logo"></span> Вернуться на главную</a></li>
                {% else %}
                    <li class="breadcrumbs__item"><a href="{{ url_for('site.index') }}" class="breadcrumbs__item-link"><span class="breadcrumbs__item-logo"></span></a></li>
                    {% for breadcrumb in breadcrumbs %}
                    <li class="breadcrumbs__item"><a href="{{ url_for(request.endpoint, path=breadcrumb[1]) }}" class="breadcrumbs__item-link">{{ breadcrumb[0] }}</a></li>
                    {% endfor %}
                {% endif %}
            </ul>
        </div>
    </div>
{% endmacro %}

templates/macros/__categories.html
{% macro render_categories_list(categories) %}

    {% for category in categories %}
        {% with c = category %}
            {% if c|is_list %}
            {% set category, childs = c %}
            {% else %}
            {% set category = c %}
            {% endif %}
            <li class="sidemenu__item{% if category.slug in request.path %} sidemenu__item--active{% endif %}">
                <a href="{{ url_for('site.dispatcher', path=category.path) }}" class="sidemenu__item-link">{{ category.name }} {% if category.get_offers_count %}<span class="sidemenu__item-count">{{ category.get_offers_count }}</span>{% endif %} </a>
                {% if childs %}
                <ul>
                    {{ render_categories_list(childs) }}
                </ul>
                {% endif %}
            </li>
        {% endwith %}
    {% endfor %}

{% endmacro %}


{% macro render_pagination(pagination, endpoint) %}
    {% if pagination.pages %}
    <div class="col-2">
        {% if pagination.has_prev %}
            {% if pagination.prev_num == 1 %}
                {% set url = url_for(endpoint, **kwargs) %}
            {% else %}
                {% set url = url_for(endpoint, page=pagination.prev_num, **kwargs) %}
            {% endif %}
            <a href="{{ url }}" class="btn btn--outline btn--iconed btn--icon-arrow-left"></a>
        {% else %}
            <span class="btn btn--outline btn--iconed btn--icon-arrow-left btn--dissabled"></span>
        {% endif %}
    </div>
    <div class="col-8 text-center">
        <div class="btn-group">
            {% for page in pagination.iter_pages() %}{% if page %}{% if page != pagination.page %}<a class="btn btn--outline" href="{% if page == 1 %}{{ url_for(endpoint, **kwargs) }}{% else %}{{ url_for(endpoint, page=page, **kwargs) }}{% endif %}">{{ page }}</a>{% else %}<span class="btn btn--outline btn--active">{{ page }}</span>{% endif %}{% else %}<span class="btn btn--outline">...</span>{% endif %}{% endfor %}
        </div>
    </div>
    <div class="col-2 text-right">
        {% if pagination.has_next %}
            <a href="{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}" class="btn btn--outline btn--iconed btn--icon-arrow-right"></a>
        {% else %}
            <span class="btn btn--outline btn--iconed btn--icon-arrow-right btn--dissabled"></span>
        {% endif %}
    </div>
    {% endif %}
{% endmacro %}

templates/macros/__offers.html
{% macro render_offer(offer) %}
    {% set show_timer = kwargs.pop('show_timer', True) %}
    <li class="offers__item">
        <div class="offers__item-top">
            <div class="offers__item-wrapper">
                <div class="offers__item-picture">
                    <a href="{{ url_for('site.dispatcher', path=offer.path) }}" class="link-plain">
                        <img src="{{ offer.get_picture('medium') }}" alt="{{ offer.name }} Артикул #{{ offer.articul }}" title="{{ offer.name }} всего за {{ offer.get_price() }} руб.">
                    </a>
                </div>
                <div class="offers__item-badges">
                      {% if offer.special and not offer.special.is_over %}<span class="badge-special">Акция</span><br>{% endif %}
{#                    #}
{#                    <span class="badge-new">Новинка</span>#}
                    {% if not offer.is_in_stock %}
                    <span class="badge-not-in-stock">Продано</span><br/>
                    {% endif %}
                </div>
                <favorite oid="{{ offer.id }}" favorited="{{ offer.is_in_favorites }}"></favorite>
            </div>
        </div>
        <div class="offers__item-info text-center">
            <div class="offers__item-category"><a href="{{ url_for('site.dispatcher', path=offer.parent_cached[1]) }}" class="link-plain link-grey text-small">{{ offer.parent_cached[0] }}</a></div>
            <div class="offers__item-name"><a href="{{ url_for('site.dispatcher', path=offer.path) }}" class="offers__item-name__link">{{ offer.name }}</a></div>
            <div class="offers__item-price{% if offer.special and not offer.special.is_over %} offers__item-price--special{% endif %}">{% if offer.special and not offer.special.is_over %}<span class="offers__item-oldprice">{{ offer.get_oldprice|smart_round }}</span>{% endif %}{{ offer.get_price()|smart_round }} руб.</div>
            <div class="offers__item-buttons">
            {% if offer.is_in_stock %}
            <button riot-tag="add-to-cart" id="{{ offer.id }}" {% if offer.id in g.added_to_cart %}isadded="true" {% endif %}class="btn"><span class="btn__text"><i class="icon-16 icon--cart-white"></i>Добавить</span></button>
            <a riot-tag="quick-buy" id="{{ offer.id }}" href="" class="btn btn--grey"><input type="hidden" name="offer_id" value="{{ offer.id }}"><span class="btn__text">Купить сейчас</span></a>
            {% else %}
            <span class="btn btn--outline">Нет в наличии</span>
            {% endif %}
            </div>

            {% if show_timer and offer.special and not offer.special.is_over %}
            <div class="offers__item-countdown">
                <span class="badge-special offers__item-countdown__until">До конца акции</span>
                <div class="countdown" data-countdown="{{ offer.special.timer }}"></div>
            </div>
            {% endif %}
        </div>
    </li>
{% endmacro %}
{% macro render_cart_offer(offer, idx, from_order=False) %}
    {% set quantity = offer.quantity %}
    {% set variant = offer.variant %}
    {% set price = offer.price %}
    {% set oldprice = offer.oldprice %}
    {% set offer = offer.offer %}
    {% set variant = offer.get_variant(variant) %}
    <li class="cart-offers__item">
        <div class="cart-offers__item-picture">
            <a href="{{ url_for('site.dispatcher', path=offer.path) }}" class="link-plain"><img src="{{ offer.get_picture('small') }}" alt="{{ offer.name }}" title="{{ offer.name }}" class="cart-offers__item-image"></a>
        </div>
        <div class="cart-offers__item-title">
            <a href="{{ url_for('site.dispatcher', path=offer.path) }}">{{ offer.name }} {{ variant.name|lower }}</a>
        </div>
        <div class="cart-offers__item-price{% if oldprice > 0 %} cart-offers__item-price--special{% endif %}">
            {% if oldprice > 0 %}<span>{{ oldprice }}</span>{% endif %}
            {{ offer.get_price()|smart_round }} руб.
        </div>
        <div class="cart-offers__item-count">
            X {{ quantity }}
        </div>
        <div class="cart-offers__item-total">
            {{ offer.get_price()|smart_round * quantity }} руб.
        </div>
    </li>
{% endmacro %}

{% macro render_short_offer(offer) %}
    <li class="offers__item">
        <a href="{{ url_for('site.dispatcher', path=offer.path) }}" class="link-plain">
            <div class="offers__item-top">
                <div class="offers__item-wrapper">
                    <div class="offers__item-picture"><img src="{{ offer.get_picture('small') }}" alt="{{ offer.name }} Артикул #{{ offer.articul }}" title="{{ offer.name }} всего за {{ offer.get_price() }} руб."></div>
                </div>
            </div>
            <div class="offers__item-info">
                <div class="offers__item-name">{{ offer.name }}</div>
                <div class="offers__item-price">{{ offer.get_price()|smart_round }} руб.</div>
            </div>
        </a>
    </li>
{% endmacro %}