web/site/__init__.py
# -*- coding: utf-8 -*-

import json, random, urlparse
from datetime import datetime, timedelta
from flask import (Blueprint, abort, redirect, request,
                   url_for, session, Markup, jsonify, current_app,
                   make_response)
from flask.ext.login import current_user

from ext import csrf, cache
from modules.apishop import ApishopConfig, api_connect
from modules.catalog.models import (Category, Offer, Cart, Order, Review,
                                    Region, DeliveryMethod, PaymentMethod, RegionDelivery)
from modules.pages.models import Page
from modules.dispatcher.models import Dispatcher
from modules.catalog.dispatchers import CategoryDispatcher, OfferDispatcher, VendorDispatcher
from modules.pages.dispatchers import PageDispatcher
from modules.subscribe.models import Subscriber
from modules.banners.models import Banner

from forms import OrderForm, SubscribeForm
from helpers import render_template
from utils.text import clear_tags_and_make_lines
from utils.json import request_wants_json


site = Blueprint('site', __name__)

d_map = {
    'category': CategoryDispatcher,
    'offer': OfferDispatcher,
    'vendor': VendorDispatcher,
    'page': PageDispatcher
}


@site.context_processor
def site_context():
    return dict(current_year=datetime.now().year,
                default_title=current_app.config.get('DEFAULT_TITLE'),
                default_title_separator=current_app.config.get('DEFAULT_TITLE_SEPARATOR', ' | '),
                subscribe_form=SubscribeForm(),
                is_subscribed=session.get('is_subscribed', False))


@site.before_request
def set_permanent_session():
    session.permanent = True


# Should be commented or deleted
#
# @site.route('/email/<typ>/')
# def email(typ):
#     return render_template('email/{}.html'.format(typ))


@site.route('/')
def index():
    return render_template('index.html',
                           popular_offers=Offer.get_popular()[:8],
                           special_offers=Offer.get_special_offers()[:12],
                           banners=Banner.get_banners())


@site.route('/sitemap.xml')
def sitemap():
    url_root = request.url_root

    categories = [[urlparse.urljoin(url_root, url_for('site.dispatcher', path=cat.path)),
                   cat.updated_at.strftime('%Y-%m-%d') if cat.updated_at is not None else None]
                  for cat in Category.objects.only('path', 'updated_at').order_by('+position')]

    offers = [[urlparse.urljoin(url_root, url_for('site.dispatcher', path=o.path)),
               o.updated_at.strftime('%Y-%m-%d') if o.updated_at is not None else None]
             for o in Offer.objects.only('path', 'updated_at').order_by('+path')]

    pages = [[urlparse.urljoin(url_root, url_for('site.dispatcher', path=page.path)),
              page.updated_at.strftime('%Y-%m-%d') if page.updated_at is not None else None]
             for page in Page.objects.only('path', 'updated_at').order_by('+position')]

    now = datetime.now().strftime('%Y-%m-%d')
    temp_pages = [[urlparse.urljoin(url_root, url_for('site.{}'.format(rule))), now]
                  for rule in ('upto1000', 'specials')]

    context = {'root': [url_root, datetime.now().strftime('%Y-%m-%d')],
               'categories': categories,
               'offers': offers,
               'pages': pages,
               'temp_pages': temp_pages}

    sitemap = render_template('misc/sitemap.xml', **context)
    response = make_response(sitemap)
    response.headers['Content-Type'] = 'application/xml'

    return response


@site.route('/specials/')
def specials():
    offers = Offer.objects(special__ne=None).order_by('price.ru')
    return render_template('specials.html', offers=offers)


@site.route('/up-to-1000/')
def upto1000():
    offers = Offer.objects(price__ru__lt=1000.00,
                           available=True).order_by('-stats.populatiry')
    return render_template('upto1000.html', offers=offers)


@site.route('/search/')
def search():
    s = request.args.get('s', '')

    if s:
        offers = Offer.objects.search_text(s).order_by('$text_score')
    else:
        offers = []

    return render_template('search.html',
                           offers=offers,
                           s=s)

@site.route('/profile/')
def profile():

    return render_template('profile.html')


@site.errorhandler(404)
def page_not_found(e):
    context = {'error': e}
    context['title'] = u'Страница не найдена'
    context['error_name'] = u'Ошибка 404'
    context['error_text'] = u'Вы перешли по неправильной ссылке<br />или страница была удалена'
    return render_template('errors.html', **context), e.code


@site.errorhandler(403)
def page_not_found(e):
    context = {'error': e}
    context['title'] = u'Страница не доступна'
    context['error_name'] = u'Ошибка 403'
    context['error_text'] = u'У вас нет прав для<br />доступа к этой странице'
    return render_template('errors.html', **context), e.code


@site.route('/cart/', methods=['GET', 'POST'])
def cart():
    cart = Cart.get_or_create()

    if request.method == 'POST':
        offer_id = request.form.get('offer_id', None)

        if offer_id:
            quantity = request.form.get('quantity', 1)
            variant = request.form.get('variant', None)
            cart.add_offer(offer_id, quantity, variant)

            return redirect(url_for('site.cart'))

    return render_template('cart.html')


@site.route('/order/', defaults={'order_id': None}, methods=['POST'])
@site.route('/order/<order_id>/')
def order(order_id=None):
    if not order_id and request.method == 'POST':
        cart = Cart.get_or_create()
        order_id = cart.send_order(request.form)
        if order_id:
            return json.dumps(dict(order_id=order_id, backurl=url_for('site.order', order_id=order_id)))
        else:
            error = u'Что-то пошло не так и заказ не отправился'
            return json.dumps(dict(error=error))

    order = Order.objects.get_or_404(id=order_id)

    region_id = order.userinfo.get('region_id', None)
    payment_id = order.userinfo.get('payment_method', None)
    delivery_id = order.userinfo.get('delivery_method', None)

    region = Region.objects(id=region_id).first() if region_id else None
    payment = PaymentMethod.objects(id=payment_id).first() if payment_id else None
    delivery = DeliveryMethod.objects(id=delivery_id).first() if delivery_id else None

    # conf = ApishopConfig.get_config()
    # conn = api_connect(conf)
    #
    # from pprint import pprint
    # for key, item in conn.get_order_states().items():
    #     print key, item
    #
    # info = conn.get_orders_info(str(order.apishop_id))[0]
    #
    # for attr in vars(info):
    #     print u'{}\t\t\t: {}'.format(attr, getattr(info, attr, None))

    return render_template('order.html',
                           order=order,
                           region=region,
                           payment=payment,
                           delivery=delivery)


@site.route('/order/<order_id>/api/upsale/', methods=['GET', 'POST'])
def order_upsale(order_id):
    if request_wants_json():
        order = Order.objects(id=order_id).first()

        if order and request.method == 'GET':
            offers = order.get_relevant_offers(3)

            if not offers.count():
                return None

            favorites = session.get('favorites', [])
            offers = [dict(id=str(offer.id),
                           name=offer.name,
                           url=url_for('site.dispatcher', path=offer.path),
                           favorited=str(offer.id) in favorites,
                           category=dict(name=offer.parent.name,
                                         url=url_for('site.dispatcher',
                                                     path=offer.parent.path)),
                           price=offer.get_price(),
                           oldprice=offer.get_oldprice,
                           timer=offer.get_timer,
                           picture=offer.get_picture()) for offer in offers]

            return jsonify(offers=offers)

        if order and request.method == 'POST':
            offer_id = request.form.get('offer_id', None)
            if not offer_id:
                return jsonify(error=True)

            offer = Offer.objects(id=offer_id).first()
            if not offer:
                return jsonify(error=True)

            quantity = request.form.get('quantity', 1)
            variant_id = request.form.get('variant_id', None)
            variant = offer.get_variant(variant_id)

            sale = send_upsale(order, offer, quantity, variant)

            order.add_offer(offer, quantity, variant)

            # item = {
            #     'picture': offer.get_picture(),
            #     'name': offer.name,
            #     'price': offer.get_price(),
            #     'quantity': quantity,
            #     'total': offer.get_price() * quantity,
            #     'url': url_for('site.dispatcher', path=offer.path),
            # }

            return jsonify(error=False)

    return abort(404)


@site.route('/cart/api/', defaults={'offer_id': None}, methods=['POST'])
@site.route('/cart/api/<offer_id>/', methods=['POST'])
@csrf.exempt
def cart_api(offer_id=None):

    if offer_id:
        variants = []
        offer = Offer.objects(id=offer_id).first()
        if offer:
            variants = [dict(name=variant.name,
                             count=variant.store_count,
                             id=variant.aid) for variant in offer.variants]

        return json.dumps(dict(variants=variants))
    else:
        cart = Cart.get_or_create()
        form = request.form

        offer_id = form.get('offer_id', None)
        if offer_id:
            remove = True if form.get('remove') == 'true' else False
            variant_id = form.get('variant_id')
            if remove:
                cart.remove_offer(offer_id, variant_id)
            else:

templates/base.html
{% from 'macros/__offers.html' import render_short_offer %}
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="google-site-verification" content="tEE2uwiBxJjwFZM-gXRWw3RpDmOMfvzlN_gvm_fdqN0" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="description" content="{% block description %}{% endblock %}">
{#    <meta name=viewport content="width=device-width, initial-scale=1">#}
    {% block extra_meta %}
    
    {% endblock %}
    {% block opengraph %}
    
    {% endblock %}
    <title>{% block title %}{{ default_title }}{% endblock %}</title>
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="icon" href="/favicon.png" sizes="32x32" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"/>
    {% block extrastyles %}
    {% endblock %}
</head>
<body>
    <modal-window></modal-window>
    {% if current_user.is_admin %}
    <style>
        .clearfix:after { content: ''; clear: both; display: block; }
        .admin-block { padding: 5px 20px; background-color: #333; color: #ccc; font-size: 13px; }
        .admin-block a { color: #fff; }
        .admin-block a:hover { color: lightblue; }
        .spasor { display: inline-block; padding: 0 0 0 15px; }
    </style>
    <div class="admin-block clearfix" style="">
        <div style="float: left;">
            Админ
            <span class="spasor"><a href="{{ url_for('admin.catalog') }}">Каталог</a></span>
            {% if category %}<span class="spasor"><a href="{{ url_for('admin.catalog.category.edit', category_id=category.id) }}">{{ category.name }}</a></span>{% endif %}
            {% if offer %}<span class="spasor"><a href="{{ url_for('admin.catalog.offer.edit', offer_id=offer.id) }}">{{ offer.id }}: {{ offer.name }}</a> <span class="js-copy">%% link_to_offer {{ offer.id }} %%</span></span>{% endif %}
            {% if page %}<span class="spasor"><a href="{{ url_for('admin.pages.edit', id=page.id) }}">{{ page.name }}</a></span>{% endif %}
        </div>
        <div style="float: right;"><a href="{{ url_for('security.logout') }}">Выйти</a></div>
    </div>
    {% endif %}
    <div class="layout">
        <div class="layout__main">
            <div class="layout__wrapper">
                <header class="header">
                    <div class="row">
                        <div class="col-2">
                            {% if request.endpoint == 'site.index' %}
                            <span class="header__logotype link-plain">{{ config.get('DEFAULT_TITLE', 'ТОП-24') }}</span>
                            {% else %}
                            <a href="{{ url_for('site.index') }}" class="header__logotype link-plain">{{ config.get('DEFAULT_TITLE', 'ТОП-24') }}</a>
                            {% endif %}
                        </div>
                        <div class="col-3">
                            <a href="tel:{{ config.get('PHONE_NUMBER')|phonofize }}" class="link-plain header__phone"><strong>{{ config.get('PHONE_NUMBER') }}</strong></a><br>
                            <span class="text-small text-grey">Круглосуточно, без выходных</span>
                        </div>
                        <div class="col-3">
                            <div class="header__iconed">
                                <div class="header__iconed-left">
                                    <i class="icon-32 icon--heart"></i>
                                </div>
                                <div class="header__iconed-right">
{#                                    <a href="{{ url_for('site.profile') }}" class="link-plain{% if request.path == url_for('site.profile') %} link-active{% endif %}">Личный кабинет</a><br>#}
                                    <span>Личный кабинет</span><br>
                                    <a href="{{ url_for('site.favorites') }}" class="link-plain {% if not session.get('favorites') or session.get('favorites')|length == 0 %}text-grey {% endif %}{% if request.path == url_for('site.favorites') %}link-active {% endif %}text-small">Отложено: <favorites></favorites></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="header__iconed" riot-tag="minified-cart" url="{{ url_for('site.cart') }}" active="{% if url_for('site.cart') == request.path %}true{% endif %}">
                                  &nbsp;
                            </div>
                        </div>
                        <div class="col-1">
                            <div class="header__search">
                                {% if request.path != url_for('site.search') %}
                                <form action="{{ url_for('site.search') }}" class="header__search-form">
                                    <input type="text" class="input" name="s" placeholder="Поиск" placeholder="{{ request.args.get('s', '') }}">
                                    <input type="submit" class="header__search-button" value="" />
                                </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </header>
                <div class="mainnav">
                    <div class="row">
                        <div class="cell-12">
                            <ul class="mainnav__list{% if has_active %} mainnav__list--has-active{% endif %}">
                                {% for category in categories%}
                                <li class="mainnav__list-item"><a href="{{ url_for('site.dispatcher', path=category.path) }}" class="mainnav__list-link{% if category.path in request.path.split('/') %} mainnav__list-link--active{% endif %}">{{ category.name }}</a></li>
                                {% endfor %}
                                <li class="mainnav__list-item mainnav__list-item--pull-right"><a href="{{ url_for('site.specials') }}" class="mainnav__list-link mainnav__list-link--specials{% if request.endpoint == 'site.specials' %} mainnav__list-link--active{% endif %}">Акции и скидки</a></li>
                                <li class="mainnav__list-item mainnav__list-item--pull-right"><a href="{{ url_for('site.upto1000') }}" class="mainnav__list-link mainnav__list-link--fresh{% if request.endpoint == 'site.upto1000' %} mainnav__list-link--active{% endif %}">Товары до 1000 руб.</a></li>
{#                                <li class="mainnav__list-item mainnav__list-item--pull-right"><a href="" class="mainnav__list-link mainnav__list-link--fresh">Новинки</a></li>#}
                            </ul>
                        </div>
                    </div>
                </div>
                <section class="content">
                    {% block content %}
                    
                    {% endblock %}
                </section>
            </div>
        </div>
        <footer class="layout__footer">
            <div class="layout__wrapper">
                {% if visited_offers %}
                <div class="row row--padding">
                    <div class="col-12">
                        <p class="h2-header">Вы смотрели</p>
                        <ul class="blocks-4 offers offers--simple js-offers-visited">
                            {% for offer in visited_offers %}
                            {{ render_short_offer(offer) }}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="grey-border"></div>
                {% endif %}
                <div class="row row--padding">
                    <div class="col-6">
                        <ul class="footer__menu">
                            {% for page in pages %}
                            <li class="footer__menu-item">
                                <a href="{{ url_for('site.dispatcher', path=page.path) }}">{{ page.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-3">
                        <a href="tel:{{ config.get('PHONE_NUMBER')|phonofize }}" class="footer__contact-link link-plain"><strong>{{ config.get('PHONE_NUMBER') }}</strong></a><br>
                    </div>
                    <div class="col-3">
                        <p class="footer__copyright text-small">Интернет-магазин «ТОП-24»<br>2014&nbsp;&mdash;&nbsp;{{ current_year }}</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</body>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}" defer></script>
{% block extrascripts %}

{% endblock %}
<script src="{{ url_for('static', filename='js/scripts.js') }}" defer></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75918345-1', 'auto');
  ga('send', 'pageview');

</script>
<script src="https://yastatic.net/share2/share.js" defer></script>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter35920460 = new Ya.Metrika({
                    id:35920460,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/35920460" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
{% if current_user.is_admin %}
<script>
    var timer = setInterval(function() {
        if ($) {
            tttt($);
            clearInterval(timer);
        }
    }, 50);

    function tttt($) {
        $('.js-copy').on('click', function() {
            var temp = $('<input/>'),
                text = $(this).text();

            $('body').append(temp);
            temp.val(text).select();
            document.execCommand('copy');
            temp.remove();
        });
    }
</script>
{% endif %}
</html>

templates/cart.html
{% from 'macros/__all.html' import render_breadcrumbs %}
{% from 'macros/__offers.html' import render_cart_offer %}
{% extends 'base.html' %}

{% block title %}
Корзина{{ default_title_separator }}{{ default_title }}
{% endblock %}

{% block extrastyles %}
<link rel="stylesheet" href="{{ url_for('static', filename='admin/plugins/select2/select2.min.css') }}"/>
<style>
    .select2-selection {
        height: 32px !important;
    }

    .select2-container--default .select2-selection--single .select2-selection__arrow {
        height: 29px;
    }

    .select2-container .select2-selection--single .select2-selection__rendered {
        padding-left: 10px;
    }
</style>
{% endblock %}

{% block content %}
{{ render_breadcrumbs() }}
<div class="row">
    <div class="col-12">
        <h1>Моя корзина</h1>
        <div riot-tag="cart" class="cart-page"></div>
    </div>
{#    <div class="col-3">#}
{#        <cart-related></cart-related>#}
{#    </div>#}
</div>
{% endblock %}

{% block extrascripts %}
<script src="{{ url_for('static', filename='admin/plugins/select2/select2.js') }}" defer></script>
{#<script src="{{ url_for('static', filename='admin/plugins/select2/select2.ru.js') }}" defer></script>#}
{% endblock %}

templates/category.html
{% from 'macros/__all.html' import render_breadcrumbs with context %}
{% from 'macros/__categories.html' import render_categories_list, render_pagination %}
{% from 'macros/__offers.html' import render_offer %}

{% extends 'base.html' %}

{% block extra_meta %}
    {% if offers.has_prev %}
        {% if offers.prev_num == 1 %}
            {% set url = url_for(request.endpoint, path=category.path)  %}
        {% else %}
            {% set url = url_for(request.endpoint, path=category.path, page=offers.prev_num) %}
        {% endif %}
        <link rel="prev" href="{{ url }}" />
    {% endif %}
    {% if offers.has_next %}
        <link rel="next" href="{{ url_for(request.endpoint, path=category.path, page=offers.next_num) }}" />
    {% endif %}

    {% if category_root_url %}
        <link rel="canonical" href="{{ category_root_url }}" />
    {% endif %}
{% endblock %}

{% block description %}Отличный выбор товаров категории &laquo;{{ category.name }}&raquo; по низким ценам в интернет-магазине ТОП-24. Удобная доставка и оплата.{% endblock %}

{% block title %}
{{ category.get_title }}{{ default_title_separator }}{{ default_title }}
{% endblock %}

{% block content %}
{{ render_breadcrumbs() }}
<div class="row">
    <div class="col-3 col--padding-r-30">
        <ul class="sidemenu">
            {{ render_categories_list(tree) }}
        </ul>
        {% if not is_subscribed %}
        <div class="subscribe subscribe--side row--margin">
            <form action="{{ url_for('site.subscribe') }}" method="post" class="col--padding-20">
                <div>
                    <p class="h2-header subscribe__header">Подпишись</p>
                    <p class="subscribe__text">и получай информацию о будущих акциях и скидках!</p>
                    <div class="inputs-group row--padding-sm">
                       {{ subscribe_form.name(class_='input', placeholder=subscribe_form.name.label.text) }}
                       {{ subscribe_form.email(class_='input', placeholder=subscribe_form.email.label.text) }}
                    </div>
                    <ul class="subscribe__errors"></ul>
                    <input type="submit" class="btn btn--grey btn--enter btn--full-width" value="Подписаться">
                </div>
            </form>
            <div class="subscribe__overlay subscribe__overlay--hide">
                <div class="subscribe__overlay-wrapper">
                    <p class="h2-header subscribe__header">Спасибо!</p>
                    <p class="subscribe__text">Вы подписаны на рассылку акций и&nbsp;скидок</p>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="col-9">
        <h1>{{ category.name }}</h1>
        <div class="row row--padding-sm">
            <div class="col-9">
                <form>
                    {% if request.args.get('page') %}<input type="hidden" name="page" value="{{ request.args.get('page') }}">{% endif %}
                    {{ ordering_form.sort(class='js-category-sort') }}
                    {% set offers_total = offers.total %}
                    <span class="category__offers-count">{{ get_plural(offers_total, ('товар', 'товара', 'товаров')) }}</span>
                </form>
            </div>
            <div class="col-3 text-right">
                <div class="btn-group">
                    <a class="btn btn--outline btn--iconed btn--icon-grid btn--active" href=""></a><a class="btn btn--outline btn--iconed btn--icon-rows" href=""></a>
                </div>
            </div>
        </div>
        <ul class="blocks-3 offers">
            {% for offer in offers.items %}
                {{ render_offer(offer) }}
            {% endfor %}
        </ul>
        {% if category_root_url %}
        <div class="row row--padding">
            {{ render_pagination(offers, request.endpoint, path=category.path) }}
        </div>
        {% else %}
        <br><br>
        {% endif %}
        {% if category.description %}
        <div class="content__text content__text--padding-20 row--margin">
            {{ category.description|safe }}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/errors.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}{{ config.get('DEFAULT_TITLE_SEPARATOR', ' | ') }}{{ config.get('DEFAULT_TITLE') }}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon"/>
    <link rel="icon" href="{{ url_for('static', filename='favicon.png') }}" sizes="32x32" />
    <style>
        @import url('https://fonts.googleapis.com/css?family=Exo+2:400,700&subset=latin,cyrillic');

        html,
        body {
            margin: 0;
            padding: 0;
            text-align: center;
            font-family: 'Exo 2', Helvetica, Arial, Sans-Serif;
        }

        .line {
            padding: 20px 0;
            width: 60%;
            margin: 0 auto;
        }

        .line-error {
            margin: 60px auto 20px auto;
        }

        .line-logotype {
            position: relative;
        }

        .line-logotype:after {
            position: absolute;
            top: 0;
            left: 50%;
            margin-left: -125px;
            width: 250px;
            height: 108px;
            background: #fff;
            content: '';
            display: block;
            border-radius: 0 0 16px 16px;
            box-shadow: 0px 1px 20px 0px rgba(0,0,0,0.10);
        }

        .logotype {
            position: relative;
            z-index: 1;
            white-space: nowrap;
            text-indent: 9999px;
            display: inline-block;
            overflow: hidden;
            width: 159px;
            height: 63px;
            background-image: url('{{ url_for('static', filename="img/logotype.svg") }}');
            background-repeat: no-repeat;
            background-size: cover;
        }

        h1 {
            font-size: 46px;
            margin: 0 0 40px 0;
        }

        a {
            text-decoration: none;
            color: #000;
            transition: color .2s;
        }

        a:hover {
            color: #FF4432;
        }

        .ename {
            display: block;
            color: #999;
            font-size: 21px;
            font-weight: bold;
        }

        .etext {
            font-size: 21px;
        }

        .categories {
            list-style-type: none;
            margin: 0;
            padding: 0;
        }

        .categories > li {
            display: inline-block;
            margin: 10px;
        }
    </style>
</head>
<body>
    <div class="line line-logotype">
        <a href="{{ url_for('site.index') }}" class="logotype">{{ config.get('DEFAULT_TITLE', 'ТОП-24') }}</a>
    </div>
    <div class="line line-error">
        <span class="ename">{{ error_name }}</span>
        <h1>{{ title }}</h1>
        <p class="etext">{{ error_text|safe }}</p>
    </div>
    <div class="line">
        <ul class="categories">
            <li><a href="{{ url_for('site.index') }}">Главная</a></li>
            {% for category in categories %}
            <li><a href="{{ url_for('site.dispatcher', path=category.path) }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

templates/favorites.html
{% from 'macros/__all.html' import render_breadcrumbs with context %}
{% from 'macros/__offers.html' import render_offer %}

{% extends 'base.html' %}

{% block title %}
Отложенные товары{{ default_title_separator }}{{ default_title }}
{% endblock %}

{% block content %}
{{ render_breadcrumbs() }}
<div class="row">
    <div class="col-12">
        <h1>Отложенные товары</h1>
        {% if offers %}
        <div class="row--padding">
            <ul class="blocks-4 offers">
            {% for offer in offers %}
                {{ render_offer(offer) }}
            {% endfor %}
            </ul>
        </div>
        {% else %}
        <p>Вы пока не отложили для себя товаров</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/profile.html
{% from 'macros/__all.html' import render_breadcrumbs with context %}

{% extends 'base.html' %}

{% block title %}
Личный кабинет{{ default_title_separator }}{{ default_title }}
{% endblock %}

{% block content %}
{{ render_breadcrumbs() }}
<div class="row">
    <div class="col-8">
        <h1>Личный кабинет</h1>
        <p>В данный момент личный кабинет не доступен.</p>
    </div>
</div>
{% endblock %}

templates/specials.html
{% from 'macros/__all.html' import render_breadcrumbs with context %}
{% from 'macros/__offers.html' import render_offer %}

{% extends 'base.html' %}

{% block title %}
Акции и скидки{{ default_title_separator }}{{ default_title }}
{% endblock %}

{% block content %}
{{ render_breadcrumbs() }}
<div class="row">
    <div class="col-12">
        <h1>Акции и скидки</h1>
        {% if offers %}
        <br />
        <ul class="blocks-4 offers">
            {% for offer in offers %}
                {{ render_offer(offer) }}
            {% endfor %}
        </ul>
        {% else %}
        <p>Акций и скидок пока нет</p>
        {% endif %}
    </div>
</div>
{% endblock %}